services:
  - type: web
    name: krishimitra-backend
    env: python
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/v1/rag/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: MONGO_URL
        value: mongodb+srv://saniyauzma85_db_user:krishi123@cluster0.ya0cfzd.mongodb.net/krishimitra?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: SGhigIn01Pc93Ev30FTnN1353Oi0oA0saVvC1MBAfOL6A5jESk9s7s1d2qKlM_gjBuVxAbvzOMdI3fZsbrZD7A
      - key: JWT_ALGORITHM
        value: HS256
      - key: GEMINI_API_KEY
        value: AIzaSyD6ZcbQSqE8wJd9nZhVxI1hWzTTiHK5XKc
      - key: PINECONE_API_KEY
        value: pcsk_4jyofi_REVBd3Et97tPF6WAVupAZ8kLKCAvyHG2xfcEBaHrwL79k4e1k1pbiXid3Y6Yryi
      - key: PINECONE_ENVIRONMENT
        value: us-east-1
      - key: PINECONE_INDEX_NAME
        value: krishimitra-knowledge
      - key: OPENWEATHER_API_KEY
        value: 28590542f832e6676af5c3e93bf8892b
      - key: ALLOWED_ORIGINS
        value: ""
      - key: EMBEDDING_MODEL_NAME
        value: sentence-transformers/all-mpnet-base-v2
      - key: EMBEDDING_DIMENSION
        value: 768